# Media Manager Configuration Template

# Scan Settings
scan:
  # Base directories to scan for media files
  directories:
    - /path/to/movies
    - /path/to/tv_shows
  
  # File extensions to consider
  extensions:
    - .mp4
    - .mkv
    - .avi
    - .mov
    - .wmv
    - .m4v
    - .ts
  
  # Scan intervals (in minutes)
  intervals:
    full_scan: 1440  # Daily full scan
    incremental_scan: 60  # Hourly incremental scan
    api_update: 720  # API metadata update every 12 hours
  
  # Exclude patterns (regex)
  exclude_patterns:
    - '\.sample\.'
    - '/temp/'
    - '_UNPACK_'

# Database Settings
database:
  path: "./data/media_manager.db"
  backup:
    enabled: true
    path: "./data/backups/"
    interval: 1440  # Daily backup (minutes)
    keep_count: 7  # Keep last 7 backups

# API Integration
api:
  # Sonarr instances
  sonarr_instances:
    - name: "Main Sonarr"
      url: "http://localhost:8989"
      api_key: "your_sonarr_api_key"
      active: true
  
  # Radarr instances
  radarr_instances:
    - name: "Main Radarr"
      url: "http://localhost:7878"
      api_key: "your_radarr_api_key"
      active: true
  
  # OMDB API keys
  omdb_api_keys:
    - "your_omdb_api_key"
  
  # Rate limits
  rate_limits:
    omdb:
      daily_limit: 1000  # Daily API call limit

# Duration Validation
validation:
  # Tolerance for duration difference (in percentage)
  duration_tolerance: 5
  
  # Minimum duration for media files (in seconds)
  min_duration: 300  # 5 minutes
  
  # Auto-ignore patterns (regex) for validation
  ignore_patterns:
    - '\.trailer\.'
    - 'special.features'

# Dashboard Settings
dashboard:
  port: 8501
  theme: "light"
  title: "Media Manager Dashboard"
  refresh_interval: 60  # Dashboard refresh interval (seconds)
  default_view: "overview"

# Notification System
notification:
  # Windows notifications
  windows:
    enabled: true
    app_name: "Media Manager"
    icon_path: "./assets/icons/"
    duration: 5  # Notification duration in seconds
    throttle: 3  # Minimum seconds between notifications
  
  # Discord notifications
  discord:
    enabled: true
    webhook_url: "https://discord.com/api/webhooks/your_webhook_url"
    username: "Media Manager Bot"
    avatar_url: "https://example.com/avatar.png"
    dashboard_url: "http://localhost:8501"  # Link to dashboard in notifications
    throttle: 5  # Minimum seconds between notifications
  
  # Quiet hours
  quiet_hours:
    enabled: true
    start_time: "22:00"
    end_time: "08:00"
    allow_critical: true  # Allow critical notifications during quiet hours
  
  # Event categories
  events:
    # File issues
    file_corruption:
      enabled: true
      level: "ERROR"
    file_missing:
      enabled: true
      level: "WARNING"
    duration_mismatch:
      enabled: true
      level: "WARNING"
    
    # Scan events
    scan_start:
      enabled: false
      level: "INFO"
    scan_complete:
      enabled: true
      level: "INFO"
    
    # API events
    api_error:
      enabled: true
      level: "ERROR"
    api_rate_limit:
      enabled: true
      level: "WARNING"
    
    # System events
    system_start:
      enabled: true
      level: "INFO"
    system_error:
      enabled: true
      level: "CRITICAL"
    backup_complete:
      enabled: false
      level: "INFO"
    storage_low:
      enabled: true
      level: "WARNING"
      threshold: 10  # Percentage of free space

# Logging Settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./data/logs/media_manager.log"
  max_size: 10  # MB
  backup_count: 5
